create extension if not exists pgcrypto;

create table if not exists public.events (
  id text primary key,
  title text not null,
  event_date date not null,
  start_time time not null,
  end_time time not null,
  time_zone text not null
);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  event_id text not null references public.events(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 240),
  role text not null check (role in ('exec', 'jit')),
  sort_order bigint generated by default as identity,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.availability_ranges (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  start_slot smallint not null check (start_slot >= 0 and start_slot < 18),
  end_slot smallint not null check (end_slot > 0 and end_slot <= 18),
  check (end_slot > start_slot),
  unique (participant_id, start_slot, end_slot)
);

alter table public.events enable row level security;
alter table public.participants enable row level security;
alter table public.availability_ranges enable row level security;

drop policy if exists "public events read" on public.events;
create policy "public events read" on public.events for select using (true);
drop policy if exists "public participants read" on public.participants;
create policy "public participants read" on public.participants for select using (true);
drop policy if exists "public participants create" on public.participants;
create policy "public participants create" on public.participants for insert with check (event_id = 'eon-day-2026-09-29');
drop policy if exists "public participants update" on public.participants;
create policy "public participants update" on public.participants for update using (event_id = 'eon-day-2026-09-29') with check (event_id = 'eon-day-2026-09-29');
drop policy if exists "public participants delete" on public.participants;
create policy "public participants delete" on public.participants for delete using (event_id = 'eon-day-2026-09-29');
drop policy if exists "public ranges read" on public.availability_ranges;
create policy "public ranges read" on public.availability_ranges for select using (true);
drop policy if exists "public ranges create" on public.availability_ranges;
create policy "public ranges create" on public.availability_ranges for insert with check (exists (select 1 from public.participants p where p.id = participant_id and p.event_id = 'eon-day-2026-09-29'));
drop policy if exists "public ranges delete" on public.availability_ranges;
create policy "public ranges delete" on public.availability_ranges for delete using (exists (select 1 from public.participants p where p.id = participant_id and p.event_id = 'eon-day-2026-09-29'));

insert into public.events (id, title, event_date, start_time, end_time, time_zone)
values ('eon-day-2026-09-29', 'EoN Day', '2026-09-29', '14:00', '23:00', 'America/Toronto')
on conflict (id) do update set title = excluded.title, event_date = excluded.event_date, start_time = excluded.start_time, end_time = excluded.end_time, time_zone = excluded.time_zone;

insert into public.participants (id, event_id, name, role, sort_order) values
('10000000-0000-4000-8000-000000000001','eon-day-2026-09-29','max, eleanor, steven probably','exec',1),
('10000000-0000-4000-8000-000000000002','eon-day-2026-09-29','sam','exec',2),
('10000000-0000-4000-8000-000000000003','eon-day-2026-09-29','cindy','exec',3),
('10000000-0000-4000-8000-000000000004','eon-day-2026-09-29','kathleen','exec',4),
('10000000-0000-4000-8000-000000000005','eon-day-2026-09-29','aaron','exec',5),
('10000000-0000-4000-8000-000000000006','eon-day-2026-09-29','jennifer','exec',6),
('10000000-0000-4000-8000-000000000007','eon-day-2026-09-29','Ivy','exec',7),
('10000000-0000-4000-8000-000000000008','eon-day-2026-09-29','Kayshini','jit',8),
('10000000-0000-4000-8000-000000000009','eon-day-2026-09-29','Conor, Mattias, Dane, Aubrey, Tammy, Faaz, Megan, Matthew, Avery, Cedric, William, Ishan, Nathan, Zenith, Victoria, Sherlyn, Victor','jit',9),
('10000000-0000-4000-8000-000000000010','eon-day-2026-09-29','Ethan','jit',10),
('10000000-0000-4000-8000-000000000011','eon-day-2026-09-29','Manya','jit',11),
('10000000-0000-4000-8000-000000000012','eon-day-2026-09-29','Anna','jit',12),
('10000000-0000-4000-8000-000000000013','eon-day-2026-09-29','Bella','jit',13),
('10000000-0000-4000-8000-000000000014','eon-day-2026-09-29','Caitlyn, Pallas','jit',14)
on conflict (id) do update set name = excluded.name, role = excluded.role, sort_order = excluded.sort_order;

insert into public.availability_ranges (participant_id, start_slot, end_slot) values
('10000000-0000-4000-8000-000000000001',0,18),
('10000000-0000-4000-8000-000000000002',0,9),('10000000-0000-4000-8000-000000000002',15,18),
('10000000-0000-4000-8000-000000000003',0,3),('10000000-0000-4000-8000-000000000003',7,18),
('10000000-0000-4000-8000-000000000004',0,3),('10000000-0000-4000-8000-000000000004',7,18),
('10000000-0000-4000-8000-000000000005',0,3),('10000000-0000-4000-8000-000000000005',7,18),
('10000000-0000-4000-8000-000000000006',6,18),
('10000000-0000-4000-8000-000000000007',0,7),('10000000-0000-4000-8000-000000000007',11,18),
('10000000-0000-4000-8000-000000000008',4,6),('10000000-0000-4000-8000-000000000008',10,18),
('10000000-0000-4000-8000-000000000009',4,18),
('10000000-0000-4000-8000-000000000011',4,8),('10000000-0000-4000-8000-000000000011',11,18),
('10000000-0000-4000-8000-000000000012',5,18),
('10000000-0000-4000-8000-000000000013',5,9),('10000000-0000-4000-8000-000000000013',15,18),
('10000000-0000-4000-8000-000000000014',4,9),('10000000-0000-4000-8000-000000000014',15,18)
on conflict (participant_id, start_slot, end_slot) do nothing;

do $$ begin
  alter publication supabase_realtime add table public.participants;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.availability_ranges;
exception when duplicate_object then null; end $$;
